# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{crunchbase}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Tyler Cunnion}]
  s.date = %q{2011-09-18}
  s.email = %q{tyler.cunnion@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "crunchbase.gemspec",
    "lib/crunchbase.rb",
    "lib/crunchbase/api.rb",
    "lib/crunchbase/cb_object.rb",
    "lib/crunchbase/company.rb",
    "lib/crunchbase/crunch_exception.rb",
    "lib/crunchbase/investment.rb",
    "lib/crunchbase/person.rb",
    "lib/crunchbase/relationship.rb",
    "lib/crunchbase/relationships/firm_relationship.rb",
    "lib/crunchbase/relationships/person_relationship.rb",
    "spec/crunchbase/api_spec.rb",
    "spec/crunchbase/company_spec.rb",
    "spec/crunchbase/person_spec.rb",
    "spec/fixtures/brad-fitzpatrick.js",
    "spec/fixtures/steve-jobs.js",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/tylercunnion/crunchbase}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{Ruby wrapper for CrunchBase API}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

